CREATE TABLE IF NOT EXISTS public.service_queue(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    id_attendant uuid,
    id_customer uuid NOT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT now(),
    title character(70) COLLATE pg_catalog."default" NOT NULL,
    problem_description text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_service_queue PRIMARY KEY (id),
    CONSTRAINT fk_attendant_service FOREIGN KEY (id_attendant)
        REFERENCES public.attendant (id) MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
        NOT VALID,
    CONSTRAINT fk_customer_service FOREIGN KEY (id_customer)
        REFERENCES public.customer (id) MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
        NOT VALID
);

INSERT INTO public.service_queue(id_attendant, id_customer, creation_date, title, problem_description) VALUES
('41ea930d-c1c5-4f30-959e-86f310054d61', 'd778eb85-81e7-4fc6-b88f-c6ba5f40c856', '2025-03-03 19:03:25', 'Lorem Ipsum', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'),
('41ea930d-c1c5-4f30-959e-86f310054d61', '20d4d87f-ae48-4729-99b0-4eb0928134ae', '2025-03-03 19:07:05', 'Lorem Ipsum', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'),
('41ea930d-c1c5-4f30-959e-86f310054d61', '956cae6d-05af-4d94-bcc0-1a4b165a4194', '2025-03-03 19:10:32', 'Lorem Ipsum', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'),
('41ea930d-c1c5-4f30-959e-86f310054d61', '9b6c990f-8f5b-4018-9d97-f4e875341dcc', '2025-03-03 19:12:21', 'Lorem Ipsum', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'),
('41ea930d-c1c5-4f30-959e-86f310054d61', '38404aa9-d861-411c-ae68-22a00609d56c', '2025-03-03 19:13:22', 'Lorem Ipsum', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'),
('41ea930d-c1c5-4f30-959e-86f310054d61', '7ed6a857-e64d-46c6-bc52-f748d060bc77', '2025-03-03 19:15:33', 'Lorem Ipsum', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'),
('41ea930d-c1c5-4f30-959e-86f310054d61', 'e49cc498-0fba-4581-87f6-c09b59f7f5f5', '2025-03-03 19:17:21', 'Lorem Ipsum', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'),
('41ea930d-c1c5-4f30-959e-86f310054d61', '6203e6a0-c149-46fd-86dd-cf1fc149a02f', '2025-03-03 19:20:03', 'Lorem Ipsum', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'),
('41ea930d-c1c5-4f30-959e-86f310054d61', '1b4d2cc4-9e1f-403f-bfa6-f19e6b326f9a', '2025-03-03 19:22:07', 'Lorem Ipsum', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'),
('41ea930d-c1c5-4f30-959e-86f310054d61', '5c75dda5-dfb4-43cb-b649-b41340ff9294', '2025-03-03 19:25:10', 'Lorem Ipsum', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.')
;
